SUPABASE_URL = "https://ertcdieopoecjddamgkx.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVydGNkaWVvcG9lY2pkZGFtZ2t4Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc0NTk3OTk3NSwiZXhwIjoyMDYxNTU1OTc1fQ.ZjJ1CBKf8JRjtyYwSHHchPcNYsH1h65XW70LYXT4iiA"
